export const TOUR_TYPES = [
    { name: 'Domestic Tours' },
    { name: 'International Tours' }
];

export const TRAVEL_MODES = {
    'Domestic Tours': [
        { name: 'Bus Tour' },
        { name: 'Train Tour' },
        { name: 'Flight Tour' },
        { name: 'Ocean Cruise Tour' },
        { name: 'River/Lake Cruise Tour' },
        { name: 'Recreational Vehicle' },
        { name: 'Other Tour' }
    ],

    'International Tours': [
        { name: 'Flight Tour' },
        { name: 'Cruise Tour' },
        { name: 'Other Tour' }
    ]
};

export const TOUR_CATEGORIES = [
    { name: 'Adventure Tour Package' },
    { name: 'Wildlife Tours' },
    { name: 'Medical Tours' },
    { name: 'Pilgrimage Tours' },
    { name: 'Eco Tours' },
    { name: 'Cultural Tours' },
    { name: 'Cruise Tours' },
    { name: 'Wellness Tours' },
    { name: 'Family Tours' },
    { name: 'Leisure Tours' },
    { name: 'Luxury Tours' },
    { name: 'Honeymoon Tours' },
    { name: 'Business Tours' },
    { name: 'Shopping Tours' },
    { name: 'Sports Tours' },
    { name: 'Mountain Tours' },
    { name: 'Rural Tours' },
    { name: 'Beach Tours' },
    { name: 'Religious Tours' },
    { name: 'Culinary Tours' },
    { name: 'City Tours' }
];

export const TOUR_NAMES = [
    { name: 'Banglore Dayout' },
    { name: 'Munnar Trip Holiday' },
    { name: 'Banglore Holiday' },
    { name: 'KSRTC Package Munnar' },
    { name: 'Munnar Dayout' }
];
export const tours = [
    {
        packageId: "PKG100",
        createdDate: "12/10/2024, 10:00 AM",
        createdBy: "John Milikon",
        tourType: "Domestic Tours",
        travelMode: "Bus Tour",
        tourCategory: "Adventure Tour Package",
        tourName: "Kolkata Trail & Camping",
        tourLocation: "Bangalore",
        startDate: "12/03/2025",
        endDate: "15/03/2025",
        days: 5,
        nights: 4,
        status: "Active",
        rowAlert: null,
    },
    {
        packageId: "PKG101",
        createdDate: "13/10/2024, 10:00 AM",
        createdBy: "Karalo Marila",
        tourType: "Domestic Tours",
        travelMode: "Bus Tour",
        tourCategory: "Mountain Tour Package",
        tourName: "Surf Through Thrilling Waves",
        tourLocation: "Munnar",
        startDate: "12/03/2025",
        endDate: "15/03/2025",
        days: 5,
        nights: 4,
        status: "Active",
        rowAlert: null,
    },
    {
        packageId: "PKG102",
        createdDate: "14/10/2024, 10:00 AM",
        createdBy: "Sabiko Millan",
        tourType: "International Tours",
        travelMode: "Flight Tour",
        tourCategory: "Ecotourism Tour Package",
        tourName: "Adventure in Munnar",
        tourLocation: "Munnar",
        startDate: "12/03/2025",
        endDate: "15/03/2025",
        days: 5,
        nights: 4,
        status: "Inactive",
        rowAlert: "Incomplete Form",
    },
    {
        packageId: "PKG103",
        createdDate: "15/10/2024, 10:00 AM",
        createdBy: "Dumartic Masto",
        tourType: "Domestic Tours",
        travelMode: "Cruise Tour",
        tourCategory: "Leisure Tour Package",
        tourName: "Bungee Package",
        tourLocation: "Kollam",
        startDate: "12/03/2025",
        endDate: "15/03/2025",
        days: 5,
        nights: 4,
        status: "Active",
        rowAlert: null,
    },
    {
        packageId: "PKG104",
        createdDate: "16/10/2024, 10:00 AM",
        createdBy: "Paalsta Maiser",
        tourType: "Domestic Tours",
        travelMode: "Bus Tour",
        tourCategory: "Leisure Tour Package",
        tourName: "Trivandrum City Ride",
        tourLocation: "Munnar",
        startDate: "12/03/2025",
        endDate: "15/03/2025",
        days: 5,
        nights: 4,
        status: "Active",
        rowAlert: "Withdrawal Expiring",
    },
    {
        packageId: "PKG105",
        createdDate: "17/10/2024, 10:00 AM",
        createdBy: "Nawruto Master",
        tourType: "Domestic Tours",
        travelMode: "Flight Tour",
        tourCategory: "Leisure Tour Package",
        tourName: "Banclore Deluxe",
        tourLocation: "Munnar",
        startDate: "12/03/2025",
        endDate: "15/03/2025",
        days: 5,
        nights: 4,
        status: "Active",
        rowAlert: null,
    },
    {
        packageId: "PKG106",
        createdDate: "18/10/2024, 10:00 AM",
        createdBy: "Sameer",
        tourType: "Domestic Tours",
        travelMode: "Bus Tour",
        tourCategory: "Ecotourism Tour Package",
        tourName: "Munnar Holiday Package",
        tourLocation: "Munnar",
        startDate: "12/03/2025",
        endDate: "15/03/2025",
        days: 1,
        nights: 0,
        status: "Active",
        rowAlert: null,
    },
    {
        packageId: "PKG107",
        createdDate: "19/10/2024, 10:00 AM",
        createdBy: "Joseph",
        tourType: "Domestic Tours",
        travelMode: "Bus Tour",
        tourCategory: "Leisure Tour Package",
        tourName: "Kodaikanal Package",
        tourLocation: "Munnar",
        startDate: "12/03/2025",
        endDate: "15/03/2025",
        days: 1,
        nights: 0,
        status: "Active",
        rowAlert: null,
    },
    {
        packageId: "PKG108",
        createdDate: "20/10/2024, 10:00 AM",
        createdBy: "Abraham",
        tourType: "Domestic Tours",
        travelMode: "Bus Tour",
        tourCategory: "Ecotourism Tour Package",
        tourName: "Hyderabad Days",
        tourLocation: "Munnar",
        startDate: "12/03/2025",
        endDate: "15/03/2025",
        days: 1,
        nights: 0,
        status: "Active",
        rowAlert: null,
    },
    {
        packageId: "PKG109",
        createdDate: "21/10/2024, 10:00 AM",
        createdBy: "Nill Karl",
        tourType: "Domestic Tours",
        travelMode: "Bus Tour",
        tourCategory: "Leisure Tour Package",
        tourName: "Bungee Run Activity",
        tourLocation: "New Delhi",
        startDate: "12/03/2025",
        endDate: "15/03/2025",
        days: 5,
        nights: 4,
        status: "Active",
        rowAlert: null,
    },
      {
        packageId: "PKG100",
        createdDate: "12/10/2024, 10:00 AM",
        createdBy: "John Milikon",
        tourType: "Domestic Tours",
        travelMode: "Bus Tour",
        tourCategory: "Adventure Tour Package",
        tourName: "Kolkata Trail & Camping",
        tourLocation: "Bangalore",
        startDate: "12/03/2025",
        endDate: "15/03/2025",
        days: 5,
        nights: 4,
        status: "Active",
        rowAlert: null,
    },
    {
        packageId: "PKG101",
        createdDate: "13/10/2024, 10:00 AM",
        createdBy: "Karalo Marila",
        tourType: "Domestic Tours",
        travelMode: "Bus Tour",
        tourCategory: "Mountain Tour Package",
        tourName: "Surf Through Thrilling Waves",
        tourLocation: "Munnar",
        startDate: "12/03/2025",
        endDate: "15/03/2025",
        days: 5,
        nights: 4,
        status: "Active",
        rowAlert: null,
    },
    {
        packageId: "PKG102",
        createdDate: "14/10/2024, 10:00 AM",
        createdBy: "Sabiko Millan",
        tourType: "International Tours",
        travelMode: "Flight Tour",
        tourCategory: "Ecotourism Tour Package",
        tourName: "Adventure in Munnar",
        tourLocation: "Munnar",
        startDate: "12/03/2025",
        endDate: "15/03/2025",
        days: 5,
        nights: 4,
        status: "Inactive",
        rowAlert: "Incomplete Form",
    },
      {
        packageId: "PKG100",
        createdDate: "12/10/2024, 10:00 AM",
        createdBy: "John Milikon",
        tourType: "Domestic Tours",
        travelMode: "Bus Tour",
        tourCategory: "Adventure Tour Package",
        tourName: "Kolkata Trail & Camping",
        tourLocation: "Bangalore",
        startDate: "12/03/2025",
        endDate: "15/03/2025",
        days: 5,
        nights: 4,
        status: "Active",
        rowAlert: null,
    },
    {
        packageId: "PKG101",
        createdDate: "13/10/2024, 10:00 AM",
        createdBy: "Karalo Marila",
        tourType: "Domestic Tours",
        travelMode: "Bus Tour",
        tourCategory: "Mountain Tour Package",
        tourName: "Surf Through Thrilling Waves",
        tourLocation: "Munnar",
        startDate: "12/03/2025",
        endDate: "15/03/2025",
        days: 5,
        nights: 4,
        status: "Active",
        rowAlert: null,
    },
    {
        packageId: "PKG102",
        createdDate: "14/10/2024, 10:00 AM",
        createdBy: "Sabiko Millan",
        tourType: "International Tours",
        travelMode: "Flight Tour",
        tourCategory: "Ecotourism Tour Package",
        tourName: "Adventure in Munnar",
        tourLocation: "Munnar",
        startDate: "12/03/2025",
        endDate: "15/03/2025",
        days: 5,
        nights: 4,
        status: "Inactive",
        rowAlert: "Incomplete Form",
    },
      {
        packageId: "PKG100",
        createdDate: "12/10/2024, 10:00 AM",
        createdBy: "John Milikon",
        tourType: "Domestic Tours",
        travelMode: "Bus Tour",
        tourCategory: "Adventure Tour Package",
        tourName: "Kolkata Trail & Camping",
        tourLocation: "Bangalore",
        startDate: "12/03/2025",
        endDate: "15/03/2025",
        days: 5,
        nights: 4,
        status: "Active",
        rowAlert: null,
    },
    {
        packageId: "PKG101",
        createdDate: "13/10/2024, 10:00 AM",
        createdBy: "Karalo Marila",
        tourType: "Domestic Tours",
        travelMode: "Bus Tour",
        tourCategory: "Mountain Tour Package",
        tourName: "Surf Through Thrilling Waves",
        tourLocation: "Munnar",
        startDate: "12/03/2025",
        endDate: "15/03/2025",
        days: 5,
        nights: 4,
        status: "Active",
        rowAlert: null,
    },
    {
        packageId: "PKG102",
        createdDate: "14/10/2024, 10:00 AM",
        createdBy: "Sabiko Millan",
        tourType: "International Tours",
        travelMode: "Flight Tour",
        tourCategory: "Ecotourism Tour Package",
        tourName: "Adventure in Munnar",
        tourLocation: "Munnar",
        startDate: "12/03/2025",
        endDate: "15/03/2025",
        days: 5,
        nights: 4,
        status: "Inactive",
        rowAlert: "Incomplete Form",
    },
      {
        packageId: "PKG100",
        createdDate: "12/10/2024, 10:00 AM",
        createdBy: "John Milikon",
        tourType: "Domestic Tours",
        travelMode: "Bus Tour",
        tourCategory: "Adventure Tour Package",
        tourName: "Kolkata Trail & Camping",
        tourLocation: "Bangalore",
        startDate: "12/03/2025",
        endDate: "15/03/2025",
        days: 5,
        nights: 4,
        status: "Active",
        rowAlert: null,
    },
    {
        packageId: "PKG101",
        createdDate: "13/10/2024, 10:00 AM",
        createdBy: "Karalo Marila",
        tourType: "Domestic Tours",
        travelMode: "Bus Tour",
        tourCategory: "Mountain Tour Package",
        tourName: "Surf Through Thrilling Waves",
        tourLocation: "Munnar",
        startDate: "12/03/2025",
        endDate: "15/03/2025",
        days: 5,
        nights: 4,
        status: "Active",
        rowAlert: null,
    },
    {
        packageId: "PKG102",
        createdDate: "14/10/2024, 10:00 AM",
        createdBy: "Sabiko Millan",
        tourType: "International Tours",
        travelMode: "Flight Tour",
        tourCategory: "Ecotourism Tour Package",
        tourName: "Adventure in Munnar",
        tourLocation: "Munnar",
        startDate: "12/03/2025",
        endDate: "15/03/2025",
        days: 5,
        nights: 4,
        status: "Inactive",
        rowAlert: "Incomplete Form",
    },
];